### ISSUE TITLE
Volume gets distorted when using headphones and getting a notification  

### ISSUE THREAD

**Issue by charliehorseuk** [ArchiDroid/android_device_samsung_i9300#32] opened 2015-02-05 09:21 UTC
With headphones, if listening music, and receiveing a notify, the audio mixer gets crazy, the volume of the channel of the music gets super high (incredibly high) and music is distorted till I do a simple volume up or down or pause and unpause.

**Comment by MarcKe** [comment] 2015-02-05 09:35
This is actually a cm issue. Ive seen lots of patches in cm lately. Might be fixed in the next release.

**Comment by Haringstad** [comment] 2015-02-08 12:44
I can confirm this too. (The issue)

**Comment by MarcKe** [comment] 2015-02-10 06:02
I cannot reproduce it on latest builds.

**Closed by MarcKe** 2015-02-10 06:02 UTC
Labels: Bug, Confirmed, Not sure if device-based
