### ISSUE TITLE
Kerneloops: "Unable to handle kernel paging request at virtual address"

### ISSUE THREAD

**Issue by thopiekar** [ArchiDroid/android_device_samsung_i9300#108] opened 2015-05-11 09:04 UTC
How I get into this:
Run a quadrocopter simulator after I switched to max preformance via battery mode "applet". After fighing around and closing the app, I changed the mode from max preformance to powersave then to balanced (like the applet is designed) very quickly.

After that my phone crashed luckily my phone didn't hang at boot, like in #98 and I got this kerneloops. (Can also add the full last_kmsg of course..)
Btw. my phone had to optimize all the apps again, like after a ROM update.

```
<6>[169738.185044] c0 I:P:DmaAddr=@2058000 Total=28160 PrdSz=3520 #Prds=8 dma_area=0xf4270000
<6>[169738.220603] c0 notifier_call_chain : NOTIFY BAD cpufreq_stat_notifier_policy
<7>[169738.264295] c0 i2s_txctrl:Turn on
<4>[169738.504866] c2 audit: audit_lost=3812 audit_rate_limit=20 audit_backlog_limit=64
<3>[169738.504923] c2 audit: rate limit exceeded
<6>[169738.762356] c2 notifier_call_chain : NOTIFY BAD cpufreq_stat_notifier_policy
<6>[169739.188230] c0 pet_watchdog_timer_fn kicking...c0bb
<4>[169739.534765] c0 audit: audit_lost=4021 audit_rate_limit=20 audit_backlog_limit=64
<3>[169739.534831] c0 audit: rate limit exceeded
<1>[169739.703305] c0 Unable to handle kernel paging request at virtual address f33f3618
<1>[169739.703346] c0 pgd = e9774000
<1>[169739.703364] c0 [f33f3618] *pgd=00000000
<0>[169739.703390] c0 Internal error: Oops: 805 [#1] PREEMPT SMP
<4>[169739.703418] c0 Modules linked in: dhd [last unloaded: dhd](bf081418)
<4>[169739.703458] c0 CPU: 0    Not tainted  (3.0.31-CM-ArchiKernel-base-g400bba0 #1)
<4>[169739.703505] c0 PC is at do_dbs_timer+0xc4/0x8dc
<4>[169739.703533] c0 LR is at 0x155cc1
<4>[169739.703555] c0 pc : [<c0481760>]    lr : [<00155cc1>]    psr: 20010013
<4>[169739.703587] c0 sp : c9c1de88  ip : c0bf9534  fp : c9c1df2c
<4>[169739.703617] c0 r10: c17cd374  r9 : c0acfbd4  r8 : c0acfbd4
<4>[169739.703647] c0 r7 : c0b17484  r6 : 00008350  r5 : 0200b218  r4 : 00000000
<4>[169739.703682] c0 r3 : f13e8400  r2 : 00155cc0  r1 : 0000000a  r0 : ebc51e00
<4>[169739.703719] c0 Flags: nzCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment kernel
<4>[169739.703760] c0 Control: 10c5387d  Table: 6977404a  DAC: 00000015
<4>[169739.703794] c0 
<4>[169739.703806] c0 PC: 0xc04816e0:
<4>[169739.703828] c0 16e0  e1a08009 e50b6090 e3076648 eb08abaf e5943018 e34c6005 e51bc070 e50b6064
<4>[169739.703886] c0 1700  e59353c0 e51cc004 e5996044 e50b505c e1a05085 e59c2024 e599105c e50b5060
<4>[169739.703940] c0 1720  e51be05c e50bc040 e50b6074 e599c060 e51b6060 e5940008 e3a04000 e15c0001
<4>[169739.703991] c0 1740  31a0c001 e51b5064 e50b5064 e086500e e50bc094 e1a05185 e51bc048 e3086350
<4>[169739.704047] c0 1760  e7832005 e34c6005 e2800060 e50b603c e59c7018 eb08b10e e51b6048 e1a01000
<4>[169739.704103] c0 1780  e51bc03c e0875005 e5963008 e50bc03c e1a00003 e5936000 e4804060 eb08af99
<4>[169739.704159] c0 17a0  e51bc048 e5856014 e30a5dd4 e51b6064 e34c50a6 e59c3018 e50b4044 e50b6080
<4>[169739.704212] c0 17c0  e3e06000 e59323c0 e50b5058 e2822001 e58323c0 ea000025 e5983054 e3530000
<4>[169739.704266] c0 
<4>[169739.704276] c0 SP: 0xc9c1de08:
<4>[169739.704293] c0 de08  00000200 c06ac4dc c9c1de6c c9c1de20 c06ac4dc 0000040f 00000005 00008350
<4>[169739.704345] c0 de28  c0b17484 c0acfbd4 c9c1df2c c9c1de40 c005f590 c00591f0 ebc51e00 0000000a
<4>[169739.704399] c0 de48  00155cc0 f13e8400 00000000 0200b218 00008350 c0b17484 c0acfbd4 c0acfbd4
<4>[169739.704452] c0 de68  c17cd374 c9c1df2c c0bf9534 c9c1de88 00155cc1 c0481760 20010013 ffffffff
<4>[169739.704504] c0 de88  00000200 80010013 c9c1deec eb864408 00000014 00000000 eb864418 f102ca00
<4>[169739.704557] c0 dea8  c17cd3e4 eb864408 c9c1decc c9c1dec0 00000055 c17cd374 c9c1def4 c9c1ded0
<4>[169739.704609] c0 dec8  c0057648 002ab982 00155cc1 c0b18bd4 eb864400 eb8e6f40 c9c1c030 c0bf9534
<4>[169739.704662] c0 dee8  c9c1df04 eb8c4180 c9c1df1c c9c1df00 c06adb44 c02d09ec ea131340 ea131340
<4>[169739.704731] c0 
<4>[169739.704747] c0 IP: 0xc0bf94b4:
<4>[169739.704772] c0 94b4  00000000 dead4ead ffffffff ffffffff c0bf94c4 c0bf94c4 00000000 00000000
<4>[169739.704839] c0 94d4  c0bf94ac 00000000 c005bb80 00000001 00000000 00000000 dead4ead ffffffff
<4>[169739.704906] c0 94f4  ffffffff c0bf94f8 c0bf94f8 00000000 00000000 c0bf94e0 ebc67af0 00000001
<4>[169739.704973] c0 9514  003cc000 000c3500 f10bc900 00000000 00000000 dead4ead ffffffff ffffffff
<4>[169739.705047] c0 9534  00000000 00002710 ebc51e00 ebc51e80 00000019 0000c350 f13e8400 00000001
<4>[169739.705113] c0 9554  eb864500 f13885d0 00000096 c048250c c048164c 00000000 ebcf5540 c0060870
<4>[169739.705178] c0 9574  00000004 c0a7d4ac c0ad00e0 00000000 f110f880 00000000 00000003 00000000
<4>[169739.705235] c0 9594  00000000 00000000 00000000 00000000 00000000 00000000 00000010 00000003
<4>[169739.705294] c0 
<4>[169739.705305] c0 FP: 0xc9c1deac:
<4>[169739.705324] c0 deac  eb864408 c9c1decc c9c1dec0 00000055 c17cd374 c9c1def4 c9c1ded0 c0057648
<4>[169739.705376] c0 decc  002ab982 00155cc1 c0b18bd4 eb864400 eb8e6f40 c9c1c030 c0bf9534 c9c1df04
<4>[169739.705428] c0 deec  eb8c4180 c9c1df1c c9c1df00 c06adb44 c02d09ec ea131340 ea131340 c17cc760
<4>[169739.705480] c0 df0c  c17d1500 c0b17484 c9c1c030 00000000 c17cd374 c9c1df6c c9c1df30 c00c3a38
<4>[169739.705530] c0 df2c  c04816a8 c9c1df5c 00000000 c048169c 00000000 c17cc760 c17cc774 ea131350
<4>[169739.705583] c0 df4c  c0a6b718 c9c1c030 c0058d20 ea131340 c17cc760 c9c1dfac c9c1df70 c00c4168
<4>[169739.705636] c0 df6c  c00c38f0 c2903ed4 c0058d20 c0b1d160 c0058d20 00000013 c2903eb8 ea131340
<4>[169739.705693] c0 df8c  c00c3ffc 00000013 00000000 00000000 00000000 c9c1dff4 c9c1dfb0 c00c8b60
<4>[169739.705752] c0 
<4>[169739.705762] c0 R0: 0xebc51d80:
<4>[169739.705780] c0 1d80  f000088c 00000011 ebc51de8 00018180 00000000 00000000 00000000 00000000
<4>[169739.705845] c0 1da0  c06be860 c06b62c4 ebc51d00 f1195580 00000000 000001b2 00000000 00000000
<4>[169739.705905] c0 1dc0  00000001 00000000 00000000 00000000 dead4ead ffffffff ffffffff 00000000
<4>[169739.705965] c0 1de0  ebc51de0 ebc51de0 5f706d73 69666661 7974696e 73696c5f 00010074 0001477f
<4>[169739.706022] c0 1e00  000001b0 0000000a 978bdd8f 00009a60 00000039 00000000 eb864205 ebc51e1c
<4>[169739.706077] c0 1e20  ebc51e1c c0482574 c797f8b0 f1026600 020516bc f1026001 c00c2db8 ebc51e18
<4>[169739.706133] c0 1e40  ffffffff ffffffff 00000000 00000000 00000000 00000000 00000000 eb8d2400
<4>[169739.706187] c0 1e60  00000000 00000000 dead4ead ffffffff ffffffff 00000000 00000000 00000000
<4>[169739.706244] c0 
<4>[169739.706254] c0 R3: 0xf13e8380:
<4>[169739.706271] c0 8380  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[169739.706324] c0 83a0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[169739.706379] c0 83c0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[169739.706431] c0 83e0  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[169739.706489] c0 8400  000c3500 00000011 0000000b 00000032 0000000f 000000ca 000c3500 0000000e
<4>[169739.706540] c0 8420  0000000b 0000002d 00000011 000000c8 000927c0 0000000f 00000030 0000002f
<4>[169739.706598] c0 8440  00000016 00000105 0007a120 00000041 0000002c 0000000e 0000001f 0000012a
<4>[169739.706650] c0 8460  0007a120 0000005f 00000010 00000010 00000024 00000169 00124f80 00000029
<4>[169739.706703] c0 
<4>[169739.706715] c0 R7: 0xc0b17404:
<4>[169739.706735] c0 7404  00000000 00000000 c0966590 00000000 00000000 00000000 00000000 c09665a0
<4>[169739.706796] c0 7424  00000000 00000000 00000000 00000000 c096663c 00000000 00000000 00000000
<4>[169739.706857] c0 7444  00000000 c0966614 00000000 00000000 00000000 00000000 c0966600 00000000
<4>[169739.706913] c0 7464  00000000 00000000 00000000 c096662c 00000000 00000000 00000000 00000000
<4>[169739.706968] c0 7484  c0966694 00000000 00000000 00000000 00000000 c096667c 00000000 00000000
<4>[169739.707027] c0 74a4  00000000 00000000 c0966664 00000000 00000000 00000000 00000000 c096664c
<4>[169739.707086] c0 74c4  00000000 00000000 00000000 00000000 c09666bc 00000000 00000000 00000000
<4>[169739.707145] c0 74e4  00000000 c09666c8 00000000 00000000 00000000 00000000 c09666d4 00000000
<4>[169739.707202] c0 
<4>[169739.707214] c0 R8: 0xc0acfb54:
<4>[169739.707232] c0 fb54  00000000 00000000 c0acf938 c0acfcc4 00000000 00000500 c0acfb6c c0acfb6c
<4>[169739.707284] c0 fb74  c047fe0c 00000500 c0acfb7c c0acfb7c c047fdac 65776f70 76617372 00000065
<4>[169739.707337] c0 fb94  00000000 c047ffa4 00000000 00000000 00000000 c0acfcc4 c0acf938 00000000
<4>[169739.707392] c0 fbb4  00000500 c0acfbb8 c0acfbb8 c047ff44 00000500 c0acfbc8 c0acfbc8 c047fee4
<4>[169739.707450] c0 fbd4  00000000 00000064 00000064 000000c8 000000c8 0000012c 0000012c 00000000
<4>[169739.707505] c0 fbf4  00000000 0007a120 00030d40 0007a120 00030d40 0007a120 00030d40 00000000
<4>[169739.707561] c0 fc14  0000c350 00000055 00000005 00000000 00000002 00000000 00000025 0000000a
<4>[169739.707619] c0 fc34  00000014 0007a120 00030d40 00000001 00000000 00000000 00000000 00000000
<4>[169739.707679] c0 
<4>[169739.707689] c0 R9: 0xc0acfb54:
<4>[169739.707706] c0 fb54  00000000 00000000 c0acf938 c0acfcc4 00000000 00000500 c0acfb6c c0acfb6c
<4>[169739.707756] c0 fb74  c047fe0c 00000500 c0acfb7c c0acfb7c c047fdac 65776f70 76617372 00000065
<4>[169739.707805] c0 fb94  00000000 c047ffa4 00000000 00000000 00000000 c0acfcc4 c0acf938 00000000
<4>[169739.707856] c0 fbb4  00000500 c0acfbb8 c0acfbb8 c047ff44 00000500 c0acfbc8 c0acfbc8 c047fee4
<4>[169739.707908] c0 fbd4  00000000 00000064 00000064 000000c8 000000c8 0000012c 0000012c 00000000
<4>[169739.707968] c0 fbf4  00000000 0007a120 00030d40 0007a120 00030d40 0007a120 00030d40 00000000
<4>[169739.708030] c0 fc14  0000c350 00000055 00000005 00000000 00000002 00000000 00000025 0000000a
<4>[169739.708089] c0 fc34  00000014 0007a120 00030d40 00000001 00000000 00000000 00000000 00000000
<4>[169739.708143] c0 
<4>[169739.708153] c0 R10: 0xc17cd2f4:
<4>[169739.708171] c0 d2f4  00000000 014bc6f3 f2a86892 d5b55e71 99bb450d f0730f36 c17cc008 eb8c4180
<4>[169739.708238] c0 d314  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
<4>[169739.708295] c0 d334  dead4ead ffffffff ffffffff c17cd340 c17cd340 eb8d1240 00000000 bec25d2c
<4>[169739.708349] c0 d354  0000001d 21c99f5c 00000000 8544c194 00000027 00000000 00000000 eb8c4180
<4>[169739.708405] c0 d374  00000000 c17cd378 c17cd378 c048169c 00000000 00200200 020516ba c0b1c0e1
<4>[169739.708460] c0 d394  c00c2db8 c17cd374 ffffffff ffffffff 00000000 00000000 00000000 00000000
<4>[169739.708520] c0 d3b4  00000000 00000000 c17cd3bc c17cd3bc c0481470 00000000 c17cd3cc c17cd3cc
<4>[169739.708585] c0 d3d4  c04813b8 00000000 00000001 00000000 00000000 00000000 00000000 dead4ead
<0>[169739.708643] c0 Process kworker/0:0 (pid: 28030, stack limit = 0xc9c1c2f0)
<0>[169739.708680] c0 Stack: (0xc9c1de88 to 0xc9c1e000)
<0>[169739.708710] c0 de80:                   00000200 80010013 c9c1deec eb864408 00000014 00000000
<0>[169739.708761] c0 dea0: eb864418 f102ca00 c17cd3e4 eb864408 c9c1decc c9c1dec0 00000055 c17cd374
<0>[169739.708812] c0 dec0: c9c1def4 c9c1ded0 c0057648 002ab982 00155cc1 c0b18bd4 eb864400 eb8e6f40
<0>[169739.708863] c0 dee0: c9c1c030 c0bf9534 c9c1df04 eb8c4180 c9c1df1c c9c1df00 c06adb44 c02d09ec
<0>[169739.708910] c0 df00: ea131340 ea131340 c17cc760 c17d1500 c0b17484 c9c1c030 00000000 c17cd374
<0>[169739.708959] c0 df20: c9c1df6c c9c1df30 c00c3a38 c04816a8 c9c1df5c 00000000 c048169c 00000000
<0>[169739.709004] c0 df40: c17cc760 c17cc774 ea131350 c0a6b718 c9c1c030 c0058d20 ea131340 c17cc760
<0>[169739.709048] c0 df60: c9c1dfac c9c1df70 c00c4168 c00c38f0 c2903ed4 c0058d20 c0b1d160 c0058d20
<0>[169739.709092] c0 df80: 00000013 c2903eb8 ea131340 c00c3ffc 00000013 00000000 00000000 00000000
<0>[169739.709138] c0 dfa0: c9c1dff4 c9c1dfb0 c00c8b60 c00c4008 00000000 ea131340 00000000 00000000
<0>[169739.709181] c0 dfc0: c2903eb8 dead4ead ffffffff ffffffff c9c1dfd0 c9c1dfd0 00000000 c2903eb8
<0>[169739.709223] c0 dfe0: c00c8ac8 c00aa47c 00000000 c9c1dff8 c00aa47c c00c8ad4 00000000 00000000
<4>[169739.709266] c0 Backtrace: 
<4>[169739.709302] c0 [<c048169c>] (do_dbs_timer+0x0/0x8dc) from [<c00c3a38>] (process_one_work+0x154/0x4f4)
<4>[169739.709360] c0 [<c00c38e4>] (process_one_work+0x0/0x4f4) from [<c00c4168>] (worker_thread+0x16c/0x3d0)
<4>[169739.709418] c0 [<c00c3ffc>] (worker_thread+0x0/0x3d0) from [<c00c8b60>] (kthread+0x98/0x9c)
<4>[169739.709481] c0 [<c00c8ac8>] (kthread+0x0/0x9c) from [<c00aa47c>] (do_exit+0x0/0x794)
<4>[169739.709525] c0  r6:c00aa47c r5:c00c8ac8 r4:c2903eb8
<0>[169739.709565] c0 Code: e50bc094 e1a05185 e51bc048 e3086350 (e7832005) 
<4>[169739.710252] c0 ---[ end trace f80a8abe58d0ebe4 ]---
<0>[169739.710315] c0 Kernel panic - not syncing: Fatal exception
<4>[169739.710345] c0 Backtrace: 
<4>[169739.710376] c0 [<c0063ea8>] (dump_backtrace+0x0/0x118) from [<c06a2b04>] (dump_stack+0x20/0x24)
<4>[169739.710425] c0  r6:c08c6e70 r5:c08c5c80 r4:c0b1b5c8 r3:00000200
<4>[169739.710472] c0 [<c06a2ae4>] (dump_stack+0x0/0x24) from [<c06a3024>] (panic+0x84/0x1a8)
<4>[169739.710516] c0 [<c06a2fa0>] (panic+0x0/0x1a8) from [<c00642b8>] (die+0x1cc/0x1d8)
<4>[169739.710560] c0  r3:00000001 r2:c9c1dc98 r1:00000000 r0:c08c5c80
<4>[169739.710602] c0  r7:c9c1de40
<4>[169739.710625] c0 [<c00640ec>] (die+0x0/0x1d8) from [<c06a2cc0>] (__do_kernel_fault.part.4+0x74/0x84)
<4>[169739.710669] c0  r9:20010113 r8:c9c1de40 r7:c9c1de40 r6:eb9ae540 r5:00000805
<4>[169739.710716] c0 r4:f33f3618
<4>[169739.710739] c0 [<c06a2c4c>] (__do_kernel_fault.part.4+0x0/0x84) from [<c0069964>] (do_sect_fault+0x0/0x20)
<4>[169739.710782] c0  r7:eb9ae540 r3:c9c1de40
<4>[169739.710816] c0 [<c00698c8>] (do_bad_area+0x0/0x9c) from [<c0069a00>] (do_translation_fault+0x7c/0xb0)
<4>[169739.710870] c0  r7:e9774000 r6:00000000 r5:c0004000 r4:00000805
<4>[169739.710912] c0 [<c0069984>] (do_translation_fault+0x0/0xb0) from [<c005922c>] (do_DataAbort+0x48/0xac)
<4>[169739.710964] c0  r7:f33f3618 r6:c0a73f80 r5:c0069984 r4:00000805
<4>[169739.711008] c0 [<c00591e4>] (do_DataAbort+0x0/0xac) from [<c005f590>] (__dabt_svc+0x70/0xa0)
<4>[169739.711056] c0 Exception stack(0xc9c1de40 to 0xc9c1de88)
<4>[169739.711093] c0 de40: ebc51e00 0000000a 00155cc0 f13e8400 00000000 0200b218 00008350 c0b17484
<4>[169739.711152] c0 de60: c0acfbd4 c0acfbd4 c17cd374 c9c1df2c c0bf9534 c9c1de88 00155cc1 c0481760
<4>[169739.711199] c0 de80: 20010013 ffffffff
<4>[169739.711224] c0  r8:c0acfbd4 r7:c0b17484 r6:00008350 r5:00000005 r4:0000040f
<4>[169739.711283] c0 [<c048169c>] (do_dbs_timer+0x0/0x8dc) from [<c00c3a38>] (process_one_work+0x154/0x4f4)
<4>[169739.711331] c0 [<c00c38e4>] (process_one_work+0x0/0x4f4) from [<c00c4168>] (worker_thread+0x16c/0x3d0)
<4>[169739.711391] c0 [<c00c3ffc>] (worker_thread+0x0/0x3d0) from [<c00c8b60>] (kthread+0x98/0x9c)
<4>[169739.711442] c0 [<c00c8ac8>] (kthread+0x0/0x9c) from [<c00aa47c>] (do_exit+0x0/0x794)
<4>[169739.711489] c0  r6:c00aa47c r5:c00c8ac8 r4:c2903eb8
<2>[169739.711554] c1 CPU1: stopping
<4>[169739.711574] c1 Backtrace: 
<4>[169739.711598] c1 [<c0063ea8>] (dump_backtrace+0x0/0x118) from [<c06a2b04>] (dump_stack+0x20/0x24)
<4>[169739.711639] c1  r6:c00582c8 r5:c0a6b718 r4:00000001 r3:00000200
<4>[169739.711683] c1 [<c06a2ae4>] (dump_stack+0x0/0x24) from [<c00597ac>] (do_IPI+0x2a4/0x2bc)
<4>[169739.711729] c1 [<c0059508>] (do_IPI+0x0/0x2bc) from [<c005f640>] (__irq_svc+0x80/0x160)
<4>[169739.711768] c1 Exception stack(0xd7eb9cf8 to 0xd7eb9d40)
<4>[169739.711800] c1 9ce0:                                                       eb8eb640 000009c0
<4>[169739.711845] c1 9d00: 00000000 00000000 eb8eb000 000080d0 c0302468 00001000 a00f0013 f1002580
<4>[169739.711888] c1 9d20: d7eb8008 d7eb9d84 00000000 d7eb9d44 00000000 c02c01a0 200f0013 ffffffff
<4>[169739.711942] c1 [<c0170524>] (kmem_cache_alloc_trace+0x0/0x200) from [<c0302468>] (n_tty_open+0x90/0xf4)
<4>[169739.711990] c1 [<c03023d8>] (n_tty_open+0x0/0xf4) from [<c03065e4>] (tty_ldisc_open.isra.5+0x70/0xcc)
<4>[169739.712038] c1  r5:c8f3c0dc r4:c8f3c000
<4>[169739.712067] c1 [<c0306574>] (tty_ldisc_open.isra.5+0x0/0xcc) from [<c0306c00>] (tty_ldisc_hangup+0x16c/0x29c)
<4>[169739.712111] c1  r6:00000002 r5:c8f3c018 r4:c8f3c000 r3:c2f9bde0
<4>[169739.712159] c1 [<c0306a94>] (tty_ldisc_hangup+0x0/0x29c) from [<c02fed78>] (__tty_hangup+0x120/0x3bc)
<4>[169739.712204] c1  r8:00000000 r7:c8f3c184 r6:c6455b40 r5:c8f3c17c r4:c8f3c000
<4>[169739.712250] c1 [<c02fec58>] (__tty_hangup+0x0/0x3bc) from [<c02ff02c>] (tty_vhangup+0x18/0x1c)
<4>[169739.712302] c1 [<c02ff014>] (tty_vhangup+0x0/0x1c) from [<c03085e8>] (pty_close+0x104/0x144)
<4>[169739.712345] c1 [<c03084e4>] (pty_close+0x0/0x144) from [<c0300158>] (tty_release+0x120/0x510)
<4>[169739.712388] c1  r4:c8f3e800 r3:c03084e4
<4>[169739.712419] c1 [<c0300038>] (tty_release+0x0/0x510) from [<c0179578>] (fput+0xe0/0x218)
<4>[169739.712462] c1 [<c0179498>] (fput+0x0/0x218) from [<c0175b10>] (filp_close+0x68/0x8c)
<4>[169739.712504] c1 [<c0175aa8>] (filp_close+0x0/0x8c) from [<c0175be8>] (sys_close+0xb4/0xec)
<4>[169739.712548] c1  r6:eb9a34a0 r5:eb9a3460 r4:00000021 r3:00000200
<4>[169739.712589] c1 [<c0175b34>] (sys_close+0x0/0xec) from [<c005fee0>] (__sys_trace_return+0x0/0x20)
<4>[169739.712633] c1  r7:00000006 r6:00000021 r5:00000000 r4:00000000
<2>[169739.712673] c2 CPU2: stopping
<4>[169739.712691] c2 Backtrace: 
<4>[169739.712715] c2 [<c0063ea8>] (dump_backtrace+0x0/0x118) from [<c06a2b04>] (dump_stack+0x20/0x24)
<4>[169739.712757] c2  r6:c00582c8 r5:c0a6b718 r4:00000002 r3:00000000
<4>[169739.712801] c2 [<c06a2ae4>] (dump_stack+0x0/0x24) from [<c00597ac>] (do_IPI+0x2a4/0x2bc)
<4>[169739.712844] c2 [<c0059508>] (do_IPI+0x0/0x2bc) from [<c005f640>] (__irq_svc+0x80/0x160)
<4>[169739.712886] c2 Exception stack(0xf10dbf18 to 0xf10dbf60)
<4>[169739.712918] c2 bf00:                                                       3c9ef3a7 55505821
<4>[169739.712961] c2 bf20: 01678ae7 00059e2b c0b18bb8 00000000 c17dc1b8 f10da008 c17dc1c8 c0bf957c
<4>[169739.713006] c2 bf40: 00000002 f10dbf84 55505821 f10dbf60 c00d3d28 c0074ad4 800f0013 ffffffff
<4>[169739.713059] c2 [<c0074a8c>] (exynos4_enter_idle+0x0/0x188) from [<c0483524>] (cpuidle_idle_call+0xe4/0x354)
<4>[169739.713103] c2  r5:00000000 r4:c0b184e4
<4>[169739.713135] c2 [<c0483440>] (cpuidle_idle_call+0x0/0x354) from [<c0060cac>] (cpu_idle+0xd0/0x100)
<4>[169739.713186] c2 [<c0060bdc>] (cpu_idle+0x0/0x100) from [<c069f638>] (secondary_start_kernel+0x13c/0x140)
<4>[169739.713235] c2  r7:c0b18670 r6:10c0387d r5:c0a99d98 r4:00000002
<4>[169739.713280] c2 [<c069f4fc>] (secondary_start_kernel+0x0/0x140) from [<4069ef34>] (0x4069ef34)
<4>[169739.713321] c2  r5:00000015 r4:48c2806a
<2>[169739.713345] c3 CPU3: stopping
<4>[169739.713364] c3 Backtrace: 
<4>[169739.713391] c3 [<c0063ea8>] (dump_backtrace+0x0/0x118) from [<c06a2b04>] (dump_stack+0x20/0x24)
<4>[169739.713436] c3  r6:c00582c8 r5:c0a6b718 r4:00000003 r3:00000000
<4>[169739.713476] c3 [<c06a2ae4>] (dump_stack+0x0/0x24) from [<c00597ac>] (do_IPI+0x2a4/0x2bc)
<4>[169739.713522] c3 [<c0059508>] (do_IPI+0x0/0x2bc) from [<c005f640>] (__irq_svc+0x80/0x160)
<4>[169739.713564] c3 Exception stack(0xf10e5f18 to 0xf10e5f60)
<4>[169739.713591] c3 5f00:                                                       dc5d6a64 55505821
<4>[169739.713638] c3 5f20: 01678ad9 00059e2b c0b18bb8 00000000 c17e41b8 f10e4008 c17e41c8 c0bf957c
<4>[169739.713684] c3 5f40: 00000003 f10e5f84 55505821 f10e5f60 c00d3d28 c0074ad4 80070013 ffffffff
<4>[169739.713731] c3 [<c0074a8c>] (exynos4_enter_idle+0x0/0x188) from [<c0483524>] (cpuidle_idle_call+0xe4/0x354)
<4>[169739.713785] c3  r5:00000000 r4:c0b184e4
<4>[169739.713812] c3 [<c0483440>] (cpuidle_idle_call+0x0/0x354) from [<c0060cac>] (cpu_idle+0xd0/0x100)
<4>[169739.713858] c3 [<c0060bdc>] (cpu_idle+0x0/0x100) from [<c069f638>] (secondary_start_kernel+0x13c/0x140)
<4>[169739.713908] c3  r7:c0b18670 r6:10c0387d r5:c0a99d98 r4:00000003
<4>[169739.713946] c3 [<c069f4fc>] (secondary_start_kernel+0x0/0x140) from [<4069ef34>] (0x4069ef34)
<4>[169739.713987] c3  r5:00000015 r4:41ff406a
<6>[169739.714022] c0 notifier_call_chain : NOTIFY BAD sec_debug_panic_handler
<0>[169739.714061] c0 Rebooting in 1 seconds..
<7>[169739.820784] c0 i2s_txctrl: Turn Off - spr is no active
<0>[169740.711953] c0 sec_reboot (104, emergency)
```

**Comment by JustArchi** [comment] 2015-05-12 01:07
Our kernel is too old, until someone points out proper commit fixing this issue, it's "won't fix" for me.

**Comment by JustArchi** [comment] 2015-05-22 15:47
Can't reproduce this one, also even if I did then it's unlikely that I would be able to fix it. No reason to keep it open anymore, sorry.

**Closed by JustArchi** 2015-05-22 15:47 UTC
Labels: Bug, Confirmed, Wishlist
