### ISSUE TITLE
Bug: cannot exit screen-pinning mode unless nav-bar is shown

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ArchiDroid/android_device_samsung_i9300#48] opened 2015-02-21 22:44 UTC
Screen-pinning allows to be locked on a certain app (task) so that the user won't be able to go to another unless some key combination is made.
When using this feature, yet the nav-bar feature isn't enabled, you cannot exit this mode (unless you restart the OS), so you are really stuck on the selected app.

Please fix this issue.

**Comment by JustArchi** [comment] 2015-02-21 22:53
Up to @MarcKe to decide if we should close this one.

**Comment by AndroidDeveloperLB** [comment] 2015-02-21 23:11
Why "won't fix" ? 
It is a bug after all...
I'm sure that Samsung's new devices, which still have physical buttons and Lollipop, allow to exit this mode without showing the nav-bar buttons (which I'm pretty sure isn't even possible).
They probably allow to just hold the back+menu buttons.
Same goes for other devices that have physical buttons (which I don't remember any that I've seen recently).

**Comment by MarcKe** [comment] 2015-02-22 06:33
Not a device, but rom issue.

**Closed by MarcKe** 2015-02-22 06:33 UTC
Labels: Bug, Not device-based, Won't fix

**Comment by AndroidDeveloperLB** [comment] 2015-02-22 07:33
@MarcKe What does it mean? Why does it matter if it's a device or a rom issue? Surely it's possible to fix this.
It's still an issue,no? Why can't it be fixed?
or maybe that's the wrong place to write about it? if so, where should I write about it?
I don't understand. :(

**Comment by MarcKe** [comment] 2015-02-22 07:48
It is definitely an issue, but we collect device related issues here.
It can be fixed of course. I might even look at it when I have some time, but still, this is a framework issue.

**Comment by AndroidDeveloperLB** [comment] 2015-02-22 07:50
@MarcKe It's an issue on Android itself? or on CM ?  Or in what you and JustArchi have made?
Framework issue tells me that it's on Android itself, so maybe I should even post about it on Google groups.

**Comment by JustArchi** [comment] 2015-02-22 07:53
Listen, we're here working on adding proper support for i9300 in CM.

We're focusing on issues directly related to (our unofficial) i9300 support, rather than issues caused by CM. We MAY fix/want to fix some CM-upstream issues, but this is totally optional and in general such issues should be fixed by CM team, and not by us.

**Comment by MarcKe** [comment] 2015-02-22 07:55
Btw, the same issue exists on my oneplus one. It has hardware buttons and onscreen button. With hardware buttons I cannot exit screen pinning. I guess CM itself will have interest in fixing this

**Comment by AndroidDeveloperLB** [comment] 2015-02-22 07:57
@MarcKe But maybe it's an issue on Android itself, no? Since CM is heavily based on AOSP, this is probably the reason, right?

**Comment by AndroidDeveloperLB** [comment] 2015-02-22 07:58
@JustArchi OK, I didn't know that. Can you please direct me to the correct place to post the issue?

**Comment by MarcKe** [comment] 2015-02-22 07:58
Yes, its an android issue. They introduced this feature and I guess in the future CM will fix it.

**Comment by JustArchi** [comment] 2015-02-22 08:00
CM issues belong to http://jira.cyanogenmod.org/

**Comment by AndroidDeveloperLB** [comment] 2015-02-22 08:00
Thank you guys. So you think I should report it to both Google and CM ?

**Comment by JustArchi** [comment] 2015-02-22 08:04
I think that nobody will care anyway, but if you want to waste your time, go ahead.

**Comment by MarcKe** [comment] 2015-02-22 08:53
Might already be it: http://review.cyanogenmod.org/#/c/89426/

**Comment by AndroidDeveloperLB** [comment] 2015-02-22 09:00
Nice. Wait, so it was fixed yesterday (now it's 22th here) ?

**Comment by MarcKe** [comment] 2015-02-22 09:01
It has not been merged yet.

**Comment by AndroidDeveloperLB** [comment] 2015-02-22 09:03
I meant committed.  :)
