### ISSUE TITLE
Incall Audio Feeble

### ISSUE THREAD

**Issue by ajaymath** [ArchiDroid/android_device_samsung_i9300#64] opened 2015-03-17 19:32 UTC
I know there seems to be another one reported but I have no data turned on so I don't suppose its the same issue. Speaker phone works fine though.Clean install didn't fix it.  I'm sorry I couldn't catch a log , have you two ever come across this issue?

**Comment by MarcKe** [comment] 2015-03-17 20:03
What does feeble mean for you?

**Comment by PetarVlad** [comment] 2015-03-17 20:07
feeble
adjective
lacking in volume, loudness, brightness, distinctness, etc.:
a feeble voice; feeble light.

**Comment by ajaymath** [comment] 2015-03-18 10:20
thank you Petar. and yes, I can't say there is no audio nor can I say the
audio is distorted, The volume is extremely low, as if the voice is being
suppressed.

Running stock kernel, weekly 8.

**Comment by wsisback** [comment] 2015-04-09 11:55
any developments on this issue? I have the same problem.

**Comment by JustArchi** [comment] 2015-04-11 10:18
Duplicate of https://github.com/ArchiDroid/android_device_samsung_i9300/issues/20, or can't reproduce if it's not that issue.

**Closed by JustArchi** 2015-04-11 10:18 UTC
Labels: Bug, Can't reproduce, Low priority, Unconfirmed

**Comment by vnikolaenko** [comment] 2015-04-23 07:17
I have same problem.

**Comment by ajaymath** [comment] 2015-04-23 15:49
If its any help to any of you, I used Boeffla Kernel Sound to increase me
incall speaker and its quite alright now.
