### ISSUE TITLE
GPS Issue with CM12.1

### ISSUE THREAD

**Issue by zacsonskaria** [ArchiDroid/android_device_samsung_i9300#130] opened 2015-06-22 13:27 UTC
GPS does not lock properly and signal keeps dropping and hence I am not able to use any navigation system on CM12.1
I have tried the GPS Toolbox and refreshed the AGPS data, but still the problem persists.

**Comment by JustArchi** [comment] 2015-06-22 13:32
It works fine for me.

Perhaps hardware issue? Have you tried on stock ROM?

**Comment by zacsonskaria** [comment] 2015-06-22 13:34
It was working fine with Stock ROM and CM11.

**Comment by JustArchi** [comment] 2015-06-22 13:35
"It was" doesn't satisfy me, does it now?

**Comment by JustArchi** [comment] 2015-06-22 13:35
You're the only one with this issue, and if I can't reproduce it then I can assure you that nobody will fix it.

**Comment by zacsonskaria** [comment] 2015-06-22 13:37
Yes I recently switched back to CM11 and it worked fine. The issue looks similar to the one reported for Nexus5 devices --> http://forum.xda-developers.com/google-nexus-5/help/gps-dropping-signal-ota-lollipop-update-t2951515

**Comment by zacsonskaria** [comment] 2015-06-22 13:44
The issue happens only on lolipop ROM's and my GPS works fine on any KitKat based ROM's. I have been testing this from the first release of CM12 and it still exist on the latest build.

**Comment by zacsonskaria** [comment] 2015-06-22 13:50
Please let me know if you want me to try some fixes on my device.

**Comment by JustArchi** [comment] 2015-06-22 13:53
GPS is fully proprietary blob. Even if indeed issue is related to LP, we won't be able to do anything without LP blob from Samsung, and unless any smdk4412 device gets one, it won't happen.

Closing this, as there is no way I can do anything about it. Sorry.

**Closed by JustArchi** 2015-06-22 13:53 UTC
Labels: Bug, Can't reproduce, Low priority, Unconfirmed

**Comment by zacsonskaria** [comment] 2015-06-23 15:12
Hi Archi,

I am on Baseband XXUGMK6. Do you think that this would be the culprit for
the GPS issue. Also appreciate if you can recommend me the best baseband of
CM12.1

Zac

On Mon, Jun 22, 2015 at 7:23 PM, Łukasz Domeradzki <notifications@github.com
> wrote:

> Closed #130
> <https://github.com/ArchiDroid/android_device_samsung_i9300/issues/130>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArchiDroid/android_device_samsung_i9300/issues/130#event-336722345>
> .
>



-- 

*Thanks & Regards,*
*Zacson Skaria*

**Comment by JustArchi** [comment] 2015-06-23 15:14
This goes outside of this issue and won't be discussed here.

Baseband is not connected with the modem.

**Comment by zacsonskaria** [comment] 2015-06-29 06:56
Hey,
I just updated my baseband, resintalled CM12.1 and bingo... my GPS is back
on track. So far no issues at all.
Thanks a lot for your efforts. You may want to share this for any other
users reporting similar issues.

Zac

On Tue, Jun 23, 2015 at 8:44 PM, Łukasz Domeradzki <notifications@github.com
> wrote:

> This goes outside of this issue and won't be discussed here.
>
> Baseband is not connected with the modem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArchiDroid/android_device_samsung_i9300/issues/130#issuecomment-114539696>
> .
>



-- 

*Thanks & Regards,*
*Zacson Skaria*
