### ISSUE TITLE
Miracast: Feedback on encoding issues

### ISSUE THREAD

**Issue by thopiekar** [ArchiDroid/android_device_samsung_i9300#141] opened 2015-08-11 09:46 UTC
Just tested miracast performance with the latest build, as the changelog says that there was work done on improving it.
In difference to build 12 (or even prior builds) the transmission seems to be now more responsive, but, as you might notice from the video I uploaded [1], the audio and video stream still have some issues.
In prior builds fragments like in (0:24) didn't appear, but the framerate was much slower. Wouldn't say that there are great changes to the audio quality until then.

Hope the recorded video about the problem is helping more than poor description of what I see :smiley: 

[1] https://youtu.be/0KpiP_qwApk

**Comment by JustArchi** [comment] 2015-08-11 18:01
This is most likely caused by never ending story with HWC working not that well. You can notice similar problems e.g. during Setup Wizard with "Next" buttons sometimes being covered with hwc trash.

Marking this as "won't fix" because I know that I won't be able to fix it with my knowledge and latest willings to work on exynos crap. Perhaps you could contact with Dhiru from NamelessROM as they might still work for i9300, and I always cherry-pick fixes from them regarding i9300.

http://forum.xda-developers.com/galaxy-s3/orig-development/rom-namelessrom-t2939673

Sorry.

**Comment by thopiekar** [comment] 2015-08-11 18:18
No problem. I'm glad that you still take care about our device. Our HWC
were always horrible, but while browsing the web our HWC is not the only
which causes headaches.

So I believe the codebase of the NamelessROM and our CM12.1 is early the
same. Will try to contact him.

Thanks!

**Comment by JustArchi** [comment] 2015-08-11 18:35
Indeed it is. Our sources are very similar regarding support for i9300 so it's safe to assume that bugs here are bugs in Nameless and vice versa. Of course, you should still check on their latest ROM if issue is still there just to be safe.

**Comment by thopiekar** [comment] 2015-09-05 17:40
Memory tweaks in the last build also fixed the issues in Miracast streaming.
Sometimes it is laggy but I beleave it is because of my old Adapter, which also does not have an external antenna.

Many thanks for fixing this!

**Closed** 2015-09-19 22:57 UTC
Labels: Bug, Confirmed, Low priority, Won't fix
