### ISSUE TITLE
Backlight illuminate

### ISSUE THREAD

**Issue by Picoloz** [ArchiDroid/android_device_samsung_i9300#31] opened 2015-02-04 15:52 UTC
When Illuminate buttons is checked, the backlights stays turned on (not off).

**Comment by MarcKe** [comment] 2015-02-04 18:24
Press the power button once. Then it wont turn on again.

**Comment by MarcKe** [comment] 2015-02-05 08:19
Currently Im unsure if this can be fixed if we want to keep the samsung stock behaviour at the same time.
Im talking about the fact that the button backlights dont light up when you touch the screen.
The problem is the kernel only gets the message from the rom: light on or light off. The kernel will also check at the same time if the hardware buttons actually have been pressed (in a different function). If they were touched, light up the button backlights. If not, do nothing. The rom will still send the "lights off" command after the timeout that is set in the rom and turn the lights off if needed.
The problem occurs when you disable the backlighting in the rom. The kernel will at first still check if the buttons have been pressed and light them up, but the rom wont send any "lights off" command anymore. The lights will stay turned on, until you actually send your device to sleep (press power button). The clue here is that now the kernel will think "the lights are already lit" when the buttons are pressed and wont try to activate them again (although they are actually off). A solution would be possible if the kernel would get a message from the rom "yo kernel, I wont activate/deactivate lights anymore", then the kernel could check that and not turn on the lights at all.

**Comment by MarcKe** [comment] 2015-02-05 08:21
Going to close it for the moment.

**Closed by MarcKe** 2015-02-05 08:21 UTC

**Comment by MarcKe** [comment] 2015-02-05 19:36
Got it fixed, a bit hacky, but it works.
