### ISSUE TITLE
Radio create lots of battery drain

### ISSUE THREAD

**Issue by jack77er** [ArchiDroid/android_device_samsung_i9300#80] opened 2015-04-15 06:49 UTC
I've wondering about the battery drain of by I9300. When I checked the battery settings I see that the radio is using 60% of battery. I've never before discovered a problem with it.

Using CM12.1 WEEK2 release currently. The same issue was already mentioned within the xda dev: http://forum.xda-developers.com/showpost.php?p=60057631&postcount=122

Hope to hear soon from you and thank you for your great work!

**Comment by goldaster** [comment] 2015-04-16 13:58
I'm having the same isue, just posted it on the Q&A thread. Besides the post you say, there are other that   are having the same isue with the radio draining lot of battery on the same thread. As far as I've seen, people with that isue have like 50% of battery used by the radio, and a total battery life of aprox 4-5 hours.

May be a problem with the radio version instaled? Mine is BUEMF2 and bootloader XXEMRD.

**Comment by jack77er** [comment] 2015-04-16 14:34
Baseband: I9300XXUGNA8
Kernel CM-g4b422cf (ArchiDroid)

I'd agree with the wakelock theory since it match with the observations overnight: I've put my device into silence mode and it uses >50% battery over night doing nothing. I'll try the flight mode tonight and see what'll happen.

**Comment by JustArchi** [comment] 2015-04-16 17:25
As stated in the tags, this does not happen to me.

**Comment by BLooDLorD** [comment] 2015-04-17 09:43
Looks like you are using custom kernel, could be the problem, doesn't happen to me

**Comment by RoelD** [comment] 2015-04-17 10:07
Had this issue as well (in an earlier build of archidroid. the one with weekly 2 as base.). Mobile connection dominated my battery stats (60~70%) instead of screen. A newer build of AD with more commits related to RIL fixed my issue, so this issue will probably fixed with the next weekly as well.

**Comment by miltec007** [comment] 2015-04-18 08:22
Same issue for me mobile standby has used 50% battery overnight. I am using the standard kernel included with cm12.1 weekly 2. This happened for me with weekly 1 as well. Baseband is i9300buugnf1.

**Comment by JustArchi** [comment] 2015-04-18 22:49
Either it's fixed already, or I can't reproduce it. Let me know if it pops up again, after release of Weekly 3.

**Closed by JustArchi** 2015-04-18 22:49 UTC
Labels: Bug, Can't reproduce, Unconfirmed
